server {
    listen 8080;
    server_name localhost;

    location = / {
        return 301 /momo-store/;
    }

    location = /health {
        access_log off;
        return 200;
    }

    location /momo-store/ {
        alias /usr/share/nginx/html/momo-store/;
        try_files $uri $uri/ /momo-store/index.html;
    }
}
